# Site settings
title: Exploratory Data Analysis and Visualization
email: jcp1016@mac.com
description: 
  Blog posts for a course in exploratory data analysis and visualization 
  at Columbia University. 
baseurl: "/my-edav-site/" # the subpath of your site, e.g. /blog/
url: "http://jcp1016.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  prumaj1016

# Build settings
markdown: kramdown
